name: Publish InMemory

on: workflow_dispatch

jobs:
    build:
        name: Build and Publish
        runs-on: ubuntu-latest
        permissions:
            contents: write
            packages: write
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup .NET Core
              uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: 8.x

            - name: Install dependencies
              run: dotnet restore

            - name: Build
              run: dotnet build --no-restore --configuration Release

            - name: Test
              run: dotnet test --configuration Release

            - name: Pack
              run: dotnet pack --no-build --configuration Release

            - name: Add Nuget source
              run: |
                  dotnet nuget add source --username ${{ secrets.NUGET_USERNAME }} --password ${{ secrets.NUGET_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"

            - name: Publish
              run: dotnet nuget push ./Messaging.InMemory/bin/Release/*.nupkg --api-key ${{ secrets.NUGET_TOKEN }} --source "github"

            - name: Bump Messaging.InMemory version
              uses: KageKirin/bump-csproj-version@v0
              id: messaging_in_memory_bump_version
              with:
                  file: Messaging.InMemory/Messaging.InMemory.csproj
                  patch: true

            - name: Commit version
              run: |
                  git config --local user.email github-actions
                  git config --local user.name github-actions 
                  echo "Bump version of Messaging.InMemory to ${{ steps.messaging_in_memory_bump_version.outputs.version }}"
                  git add Messaging.InMemory/Messaging.InMemory.csproj
                  git commit -m "Bump version of Messaging.InMemory to ${{ steps.messaging_in_memory_bump_version.outputs.version }}"
                  echo "Push version changes"
                  git push
